// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');
const eslintPluginPrettierRecommended = require('eslint-plugin-prettier/recommended');
const reactCompiler = require('eslint-plugin-react-compiler');

module.exports = defineConfig([
  expoConfig,
  eslintPluginPrettierRecommended,
  reactCompiler.configs.recommended,
  {
    // expo-env.d.ts is generated by the Expo CLI, gitignored, and carries a
    // "should not be edited" notice — linting it only produces noise CI cannot
    // act on.
    ignores: ['dist/*', 'node_modules/*', 'expo-env.d.ts'],
  },
  {
    rules: {
      '@typescript-eslint/no-empty-object-type': 'off',
      // `axios.create(...)` on the default export is the documented API. The
      // rule flags it only because axios also happens to export a `create`
      // binding, which is unrelated — it is a false positive here.
      'import/no-named-as-default-member': 'off',
    },
  },
]);
